In [1]:
from alexi.pagernn import PageDataset
from pathlib import Path

In [2]:
import torch
from torch.utils.data import DataLoader

In [3]:
ds = PageDataset(Path("../data/train/").glob("*.csv"))

In [5]:
data_loader = DataLoader(ds, batch_size=8, shuffle=False, collate_fn=lambda x: x)

In [6]:
batch = next(iter(data_loader))
feats, targets = zip(*batch)
targets

(tensor([1, 2, 2, 2, 2], dtype=torch.int32),
 tensor([1, 2, 2, 2, 2, 2, 2], dtype=torch.int32),
 tensor([5, 6, 6, 6, 6, 6, 6], dtype=torch.int32),
 tensor([5, 6, 6, 6, 6, 6, 6], dtype=torch.int32),
 tensor([5, 6, 6, 6, 6, 6, 6], dtype=torch.int32),
 tensor([5, 6, 6, 6, 6, 6, 6], dtype=torch.int32),
 tensor([5, 6, 6, 6, 6, 6, 6], dtype=torch.int32),
 tensor([5, 6, 6, 6, 6, 6, 6], dtype=torch.int32))

In [4]:
from torch.nn.utils.rnn import pad_sequence, pack_padded_sequence, pad_packed_sequence

In [9]:
feats = pad_sequence(feats, batch_first=True)
lens = [len(x) for x in targets]
targets = pad_sequence(targets, batch_first=True)
targets = pack_padded_sequence(targets, lens, batch_first=True, enforce_sorted=False)
targets

PackedSequence(data=tensor([1, 1, 5, 5, 5, 5, 5, 5, 2, 2, 6, 6, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6, 6, 6,
        2, 2, 6, 6, 6, 6, 6, 6, 2, 2, 6, 6, 6, 6, 6, 6, 0, 2, 6, 6, 6, 6, 6, 6,
        0, 2, 6, 6, 6, 6, 6, 6], dtype=torch.int32), batch_sizes=tensor([8, 8, 8, 8, 8, 8, 8]), sorted_indices=tensor([0, 1, 2, 3, 4, 5, 6, 7]), unsorted_indices=tensor([0, 1, 2, 3, 4, 5, 6, 7]))

In [11]:
pad_packed_sequence(targets, batch_first=True)

(tensor([[1, 2, 2, 2, 2, 0, 0],
         [1, 2, 2, 2, 2, 2, 2],
         [5, 6, 6, 6, 6, 6, 6],
         [5, 6, 6, 6, 6, 6, 6],
         [5, 6, 6, 6, 6, 6, 6],
         [5, 6, 6, 6, 6, 6, 6],
         [5, 6, 6, 6, 6, 6, 6],
         [5, 6, 6, 6, 6, 6, 6]], dtype=torch.int32),
 tensor([7, 7, 7, 7, 7, 7, 7, 7]))